trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   nivs-custom-devices
      name:       ni/niveristand-custom-device-build-tools

stages:
  - template: azure-templates/stages.yml@niveristand-custom-device-build-tools
    parameters:
      lvVersionsToBuild:
        - version: '2024'
          bitness: '64bit'

      codegenVis:
        - 'docs\error_codes_files\Copy Errors to Built Directory.vi'

      buildSteps:
        - projectLocation: 'lv-memory-manager\LabVIEW Memory Manager.lvproj'
          buildOperation: 'ExecuteBuildSpec'
          target: 'My Computer'
          buildSpec: 'Build Source'

      releaseVersion: '26.5.0'
      buildOutputLocation: 'Built'
      archiveLocation: '\\nirvana\Measurements\VeriStandAddons\niveristand-custom-device-development-tools'
      repoName: 'niveristand-custom-device-development-tools'
      createNetCoreRepo: true
